### ISSUE TITLE
18.11.2020 The mod is not working for me 

### ISSUE THREAD

**Issue by servermeta** [warriorstar-orion/ZHM5Randomizer#1]
reinstalled the mod several times i just dont know what to do

**Comment by servermeta** [comment]
just so you know i didnt change anything in any of the folders

**Comment by warriorstar-orion** [comment]
You're going to have to provide more information. How doesn't it work? Does it crash? What are the contents of ZHM5Randomizer.log?

**Comment by servermeta** [comment]
by doesnt work i mean it doesnt randomize items also didnt change anything in the ZHM5Randomizer.log file.

**Comment by servermeta** [comment]
fixed it
