### ISSUE TITLE
Steam release support: 3.110.1

### ISSUE THREAD

**Issue by warriorstar-orion** [warriorstar-orion/ZHM5Randomizer#1]

**Comment by warriorstar-orion** [comment]
A preliminary release of the randomizer mod for use with the Steam version is available here: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.110.1-preview3

**Comment by tntren** [comment]
this does not work for me. im using steam

**Comment by tntren** [comment]
![image](https://user-images.githubusercontent.com/82964168/177841209-e56c9520-1d9d-4d91-add8-0fa108328c6d.png)

**Comment by tntren** [comment]
[2022-07-07 11:12:37.717] [console] [info] Log file initialized.
[2022-07-07 11:12:37.717] [console] [info] Success reading toml.
 is the log file

**Comment by iBowler1995** [comment]
I have it working on Steam. Thank you so much! However, if I try to play in offline mode the game crashes while loading the level. Is offline mode supposed to be supported with the mod or no?

**Comment by tntren** [comment]
can you send me like a screenshot of your retail folder so i can see what you did

**Comment by iBowler1995** [comment]
![image](https://user-images.githubusercontent.com/93746898/177870572-4e175061-b310-45c0-9966-33e114957efd.png)

I should also note, when restarting a mission the world/environment items are no longer randomized. I'm not sure if that's normal for the mod or not, as I know some don't support restarting missions directly.

**Comment by tntren** [comment]
[2022-07-07 14:10:20.148] [console] [info] Log file initialized.
[2022-07-07 14:10:20.149] [console] [info] Success reading toml.
[2022-07-07 14:10:20.150] [console] [info] Cannot open ignore list repository at F:/SteamLibrary/steamapps/common/HITMAN 3/Retail\Retail\IgnoreList.json
??? found this in a different retail folder

**Comment by warriorstar-orion** [comment]
@tntren:

> ![image](https://user-images.githubusercontent.com/82964168/177841209-e56c9520-1d9d-4d91-add8-0fa108328c6d.png)

Thanks for this, I haven't seen that release before. I'll have to see if I can get the same version from Steam. 

> mines the exact same, do i have to configure the settings first? or is it all default

You don't need to configure anything first.

> [2022-07-07 14:10:20.148] [console] [info] Log file initialized. [2022-07-07 14:10:20.149] [console] [info] Success reading toml. [2022-07-07 14:10:20.150] [console] [info] Cannot open ignore list repository at F:/SteamLibrary/steamapps/common/HITMAN 3/Retail\Retail\IgnoreList.json ??? found this in a different retail folder

There shouldn't be two retail folders. All of the files in the archive should be in `steamapps/common/HITMAN 3/Retail`.

@iBowler1995:

> I should also note, when restarting a mission the world/environment items are no longer randomized. I'm not sure if that's normal for the mod or not, as I know some don't support restarting missions directly.

This is normal, as the README states the mod stops working when the mission is restarted, replanned, or reloaded.

**Comment by tntren** [comment]
Any work on it yet?

**Comment by tntren** [comment]
Okay

**Comment by tntren** [comment]
so should i just buy the epic games version or are you gonna make the update

**Comment by warriorstar-orion** [comment]
The latest version of the randomizer has been working for EGS and Steam for some time now: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.120.0-preview2
