### ISSUE TITLE
Timestamp not recognized on Steam version 

### ISSUE THREAD

**Issue by BigDipper4200** [warriorstar-orion/ZHM5Randomizer#12]
![image](https://user-images.githubusercontent.com/124177689/216085834-d72216b3-0f38-4a83-8e02-47134bd9964a.png)

My game is fully updated and on version 3.140.0 but the mod is incompatible.

**Comment by warriorstar-orion** [comment]
Are you using Steam in a non-US region? Sometimes players on Steam get different versions of the executable. I'd need a copy of your `HITMAN3.exe` to update the mod to work with it. If you'd like to assist you can e-mail it to orion at snowfrost dot garden.

**Comment by warriorstar-orion** [comment]
This version of the game is now supported in the mod as of the latest release. Thanks for helping out with this!
