### ISSUE TITLE
"Only supports Steam 1.40.0"

### ISSUE THREAD

**Issue by spiel0meister** [warriorstar-orion/ZHM5Randomizer#14]
When I start Hitman, _The Randomizer Mod does not recognize this version of Hitman with PE timestamp 644D2E5D._ pops up, and, says, that it _"Only supports Steam 1.40.0"_ (and also other variant and EG), although the [release](https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.150.1_egs_steam) says it supports _1.50.1_.

**Comment by Darkmind7** [comment]
I've got this problem as well. Is there any way to fix this?

**Comment by warriorstar-orion** [comment]
There is a new release available here: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.170.0_egs_steam. Enjoy, and please file new issues if you encounter any problems.
