### ISSUE TITLE
Uninstalling the randomizer has bricked my game

### ISSUE THREAD

**Issue by MicahPanda** [warriorstar-orion/ZHM5Randomizer#15]
I tried to delete all files that were associated with the mod and launching the game now gives me error 0xc0000142.

**Comment by warriorstar-orion** [comment]
The only file you'd need to remove to disable the mod is `DINPUT8.dll`. It's very unlikely that removing that file would cause the game to crash. If you're still having issues, try the latest version: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.170.0_egs_steam. Please file new issues if you encounter any problems.
