### ISSUE TITLE
Outdated as of 3.160.0

### ISSUE THREAD

**Issue by dektro** [warriorstar-orion/ZHM5Randomizer#17]
The new update means the mod still needs another patch. Also is there's no other way to teach us how to update it our selves?

**Comment by warriorstar-orion** [comment]
There is a new release available here: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.170.0_egs_steam. Enjoy, and please file new issues if you encounter any problems.

I will probably release instructions on how to update it but it's kind of an enormous pain in the ass I don't want to subject anyone else to. I'm also looking into trying to make it an SMF mod, but that's a stretch goal.
