### ISSUE TITLE
When you will release a new patch?

### ISSUE THREAD

**Issue by twikipediaa** [warriorstar-orion/ZHM5Randomizer#19]
@warriorstar-orion ive tried old version depots of hitman , but that doesnt even work, are you planning to update the mod this month>

**Comment by warriorstar-orion** [comment]
There is a new release available here: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.170.0_egs_steam. Enjoy, and please file new issues if you encounter any problems.
