### ISSUE TITLE
Uninstallation Error

### ISSUE THREAD

**Issue by Flonky** [warriorstar-orion/ZHM5Randomizer#2]
Hi, i tested out the randomizer and wanted to play normally again so i deleted the files i added, but now its throwing an error.
The error is after the shell like window pops up which writes "fpDirecctInput8Create: 0x7ff966708f80". The error windows outputs after that is "0xc0000142"

**Comment by Flonky** [comment]
The issue is still here and i havent found an fix yet. Can someone else help me maybe?

**Comment by warriorstar-orion** [comment]
It doesn't sound like you've deleted `DINPUT8.dll`.

**Comment by Flonky** [comment]
You where correct, thanks!
