### ISSUE TITLE
How do I get the randomizer to work?

### ISSUE THREAD

**Issue by TheDinklez** [warriorstar-orion/ZHM5Randomizer#2]
I recently got Hitman 3 on pc and ever since I've been trying to get the randomizer mod to work. I've done exactly what the instructions say countless times yet each time it does absolutely nothing. I've tried past installments, downloading the source codes, and nothing has worked so far. I would really like to get this mod working, as the randomizer was one of the main reasons I got it on PC.

**Comment by warriorstar-orion** [comment]
Hi there, there is a new version with support for 3.120 and Ambrose Island: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.120.0-preview2 please try it out and let me know if it works for you.
