### ISSUE TITLE
Hitman Steam 3.170.1

### ISSUE THREAD

**Issue by KatrinaAS** [warriorstar-orion/ZHM5Randomizer#20]
Hi
Sadly there is already a 3.170.1 that was released a week or so ago this will no longer work on that copy

**Comment by warriorstar-orion** [comment]
goddamnit. okay I'll get that out in a few days.

**Comment by warriorstar-orion** [comment]
Just pushed a new release: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.170.1_egs_steam

Let me know if you have any issues with it.

**Comment by KatrinaAS** [comment]
> Just pushed a new release: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.170.1_egs_steam
> 
> Let me know if you have any issues with it.

Works well thankyou!
