### ISSUE TITLE
pls update it :3

### ISSUE THREAD

**Issue by Sentakuu** [warriorstar-orion/ZHM5Randomizer#24]
could u update pleaseeee :( i wanna play it with other mods too but i got steam latest version so it doesnt work if u can update i would be glad man.

**Comment by warriorstar-orion** [comment]
I've just released a version for v3.190.0. https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.190.0

Note that if you have a Steam installation it may error out at first, if it does provide the error message here and I'll update the mod.

**Comment by Sentakuu** [comment]
![image](https://github.com/warriorstar-orion/ZHM5Randomizer/assets/87421108/36c2bd59-f3ff-4563-ac8e-ab1ae8d415d4)

**Comment by Sentakuu** [comment]
> I've just released a version for v3.190.0. https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.190.0
> 
> Note that if you have a Steam installation it may error out at first, if it does provide the error message here and I'll update the mod.

yep it error out could u fix it please would love to try it xd i saw cheru play them od
