### ISSUE TITLE
Not working with 3.190.0

### ISSUE THREAD

**Issue by EdibleCookie** [warriorstar-orion/ZHM5Randomizer#26]
Game is not working with the above version number. Game errors out and then doesn't load with mod enabled.

**Comment by warriorstar-orion** [comment]
I've just released a version for v3.190.0. https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.190.0

Note that if you have a Steam installation it may error out at first, if it does provide the error message here and I'll update the mod.
