### ISSUE TITLE
Year 2 Ambrose Island Update

### ISSUE THREAD

**Issue by warriorstar-orion** [warriorstar-orion/ZHM5Randomizer#3]
Just creating this now so I don't get bombarded with complaints that it breaks the mod.

**Comment by watameln** [comment]
yes sirrr

**Comment by quandaledongle** [comment]
will the mod now be updated or wait for the new gamemode?

**Comment by warriorstar-orion** [comment]
I've published the initial release of the mod with support for 3.120.0.

https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.120.0

Please let me know if you encounter any problems with it.

**Comment by quandaledongle** [comment]
![2022-07-31](https://user-images.githubusercontent.com/110094392/182033754-da3e3a2e-8345-4633-ae2b-7168c3100bf3.png)

**Comment by warriorstar-orion** [comment]
> ![2022-07-31](https://user-images.githubusercontent.com/110094392/182033754-da3e3a2e-8345-4633-ae2b-7168c3100bf3.png)

@quandaledongle  Where is your version of Hitman from? Steam? Epic Games Store? Somewhere else? Are you in the US region or somewhere else?

**Comment by quandaledongle** [comment]
> > ![2022-07-31](https://user-images.githubusercontent.com/110094392/182033754-da3e3a2e-8345-4633-ae2b-7168c3100bf3.png)
> 
> @quandaledongle Where is your version of Hitman from? Steam? Epic Games Store? Somewhere else? Are you in the US region or somewhere else?

steam in europe region

**Comment by quandaledongle** [comment]
> > ![2022-07-31](https://user-images.githubusercontent.com/110094392/182033754-da3e3a2e-8345-4633-ae2b-7168c3100bf3.png)
> 
> @quandaledongle Where is your version of Hitman from? Steam? Epic Games Store? Somewhere else? Are you in the US region or somewhere else?

@warriorstar-orion I use steam, in europe.

**Comment by warriorstar-orion** [comment]
@quandaledongle thank you for providing all the info! I should be able to support this release shortly. Thanks for your patience.

**Comment by quandaledongle** [comment]
> @quandaledongle thank you for providing all the info! I should be able to support this release shortly. Thanks for your patience.

Alright thank u for replying (: 👍

**Comment by quandaledongle** [comment]
> @quandaledongle thank you for providing all the info! I should be able to support this release shortly. Thanks for your patience.

@warriorstar-orion Alright thank u fir replying (: 👍

**Comment by warriorstar-orion** [comment]
@quandaledongle would you kindly try the following release to see if it works for you? https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.120.0-preview2

**Comment by quandaledongle** [comment]
> @quandaledongle would you kindly try the following release to see if it works for you? https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.120.0-preview2

@warriorstar-orion Yes it 100% works. Thx alot (:

**Comment by quandaledongle** [comment]
![2022-08-02 (1)](https://user-images.githubusercontent.com/110094392/182300795-4662f389-f477-428f-a7e7-2365728cb2cf.png)
love it
