### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by coreDeletion** [warriorstar-orion/ZHM5Randomizer#4]
I've installed the mod and verified files over 6 times now, and each time the mod never takes effect in-game

**Comment by warriorstar-orion** [comment]
Is there a file `ZHM5Randomizer.log` in your Retail path? If so, can you post its contents?

**Comment by coreDeletion** [comment]
There is no file in Retail of that name

**Comment by MeDerpWasTaken** [comment]
What maps are you trying it on?

**Comment by coreDeletion** [comment]
Miami and Whittleton Creek

**Comment by warriorstar-orion** [comment]
It should work on the main missions of any destination. If there's no log file, and you don't see a console window appear at the start of the game, the mod isn't getting hooked into the game process.

I know you say you tried six times, but I need to double check the files are in the right place. The contents of your `\Retail` directory should include:

- `IgnoreList.json`
- `DefaultItemPools.json`
- `Repository.json`
- `hitman_randomizer.toml`
- `DINPUT8.dll`

If there's a `dx12Retail` path in your HITMAN2 directory, you may need to copy the files into there as well.

**Comment by coreDeletion** [comment]
All the files mentioned are there, and I've copied the files to dx12Retail

**Comment by MeDerpWasTaken** [comment]
You're supposed to copy it into retail, even for dx12

**Comment by coreDeletion** [comment]
That was already done

**Comment by warriorstar-orion** [comment]
Hmm. Are you using any other mods? Or ReShade, ENB, anything else that hooks into the game? The only reason I can think that the DLL isn't loaded at all is it's being prevented from some other DLL.

Can you try installing the original randomizer: https://github.com/pawREP/ZHM5Randomizer/releases/tag/v1.33 and see if it works? There won't be a `.log` file or `.toml` file when it runs but you'll be able to tell once you're in mission.

**Comment by coreDeletion** [comment]
1. I am not currently nor have I ever used any other mod, other than the first iteration of this mod.

2. I will reinstall the original and get back to you on the results

**Comment by warriorstar-orion** [comment]
Closing as stale.
