### ISSUE TITLE
I have the right version on steam and it still doesnt work

### ISSUE THREAD

**Issue by Predator2505** [warriorstar-orion/ZHM5Randomizer#5]
![image](https://user-images.githubusercontent.com/68379888/182033796-0a35e2f2-a6e8-410e-9906-2fde7a18f0b4.png)
---------------------------
Randomizer Mod Failure
---------------------------
The Randomizer Mod does not recognize this version of Hitman with PE timestamp 62C5CE14.
Supported versions are:

- Hitman 3 EGS 3.120.0 (0x62C641F4)
- Hitman 3 Steam 3.120.0 (0x62C6418B)

---------------------------
OK   
---------------------------

i have version 3.120.0 please help

**Comment by Benisbenis224** [comment]
Its outdated

**Comment by Benisbenis224** [comment]
Newest steam version is 3.320.0

**Comment by Benisbenis224** [comment]
Or 3.220.0

**Comment by warriorstar-orion** [comment]
Would you kindly see if this version works for you? https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/v3.120.0-preview2
