### ISSUE TITLE
Dying Breaks map items randomization 

### ISSUE THREAD

**Issue by watameln** [warriorstar-orion/ZHM5Randomizer#6]
So all items on the map are randomised when you start. But when you die it doesn't randomize only loadouts etc.

**Comment by warriorstar-orion** [comment]
What do you mean the randomizer doesn't work when you die? Do you mean after a reload or restart of the mission, the randomizer doesn't work anymore?

**Comment by warriorstar-orion** [comment]
No response in over a year, closing.
